# Generated by Django 5.0 on 2023-12-08 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
